language: scala
sudo: required
dist: trusty
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
jdk:
  - oraclejdk7
  - oraclejdk8

matrix:
  exclude:
    - scala: 2.12.1
      jdk: oraclejdk7

services:
  - docker
before_install:
  - sudo service memcached stop
  - docker pull memcached
  - docker run -d -p 127.0.0.1:11211:11211 memcached memcached

env:
  global:
    - MAIN_SCALA_VERSION=2.11.8

script:
  - project/travis-build.sh
after_success:
  - project/travis-post-build.sh

cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
